name: Django CI

on: [ push, pull_request ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install flake8
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Run flake8
        run: flake8 . --exclude=migrations,venv,env,.venv

  test:
    runs-on: ubuntu-latest
    needs: lint

    services:
      db:
        image: postgres:16
        env:
          POSTGRES_DB: lms
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 1968919322
        ports:
          - 5432:5432
        options: >-
          --health-cmd=pg_isready
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379

    env:
      DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
      ALLOWED_HOSTS: "158.160.216.89,localhost,127.0.0.1"
      REDIS_URL: "redis://localhost:6379/0"
      CELERY_BROKER_URL: "redis://localhost:6379/0"
      CELERY_RESULT_BACKEND: "redis://localhost:6379/0"
      POSTGRES_DB: lms
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1968919322
      POSTGRES_HOST: localhost

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir -r requirements.txt

      - name: Run tests
        run: python manage.py test


  build:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Log in in DockerHub
        run: echo ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }} | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/myapp:${{ github.sha }} .

      - name: Push Docker image to Docker hub
        run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/myapp:${{ github.sha }}


  deploy:
    needs: build
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:16
        env:
          POSTGRES_DB: lms
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 1968919322
        ports:
          - 5432:5432
        options: >-
          --health-cmd=pg_isready
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379

    steps:
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Deploy to server
        env:
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          GITHUB_SHA: ${{ github.sha }}
          DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
          SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} << EOF
          echo "$DOCKER_HUB_ACCESS_TOKEN" | docker login -u "$DOCKER_HUB_USERNAME" --password-stdin
          
          # Создаём .env на сервере
          cat > .env << 'EOL'
          POSTGRES_DB=lms
          POSTGRES_USER=postgres
          POSTGRES_PASSWORD=1968919322
          POSTGRES_HOST=db
          POSTGRES_PORT=5432
          DATABASE_URL=postgres://postgres:1968919322@db:5432/lms
          DJANGO_SECRET_KEY=$DJANGO_SECRET_KEY
          DEBUG=True
          EMAIL_HOST_USER=gamidpython@yandex.ru
          EMAIL_HOST_PASSWORD=spsszwcugmgdmmzp
          CACHE_ENABLED=True
          REDIS_HOST=redis
          REDIS_PORT=6379
          ALLOWED_HOSTS=158.160.216.89,localhost,127.0.0.1
          EOL
          
          docker pull $DOCKER_HUB_USERNAME/myapp:$GITHUB_SHA
          docker stop myapp || true
          docker rm -f myapp || true
          
          docker run -d \
            --name myapp \
            -p 80:8000 \
            --env-file .env \
            $DOCKER_HUB_USERNAME/myapp:$GITHUB_SHA
          
          docker logout
          EOF



